/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as RecommendedRouteImport } from './routes/recommended'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as RoleRouteImport } from './routes/role'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as ApplicationsAppIdRouteImport } from './routes/applications/$appId'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileCertificationsRouteImport } from './routes/profile/certifications'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileEducationRouteImport } from './routes/profile/education'
import { Route as ProfileExperienceRouteImport } from './routes/profile/experience'
import { Route as ProfilePreferencesRouteImport } from './routes/profile/preferences'
import { Route as ProfileResumeRouteImport } from './routes/profile/resume'
import { Route as ProfileSkillsRouteImport } from './routes/profile/skills'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs/$jobId/index'
import { Route as JobsJobIdApplyRouteImport } from './routes/jobs/$jobId/apply'
import { Route as JobsJobIdSuccessRouteImport } from './routes/jobs/$jobId/success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendedRoute = RecommendedRouteImport.update({
  id: '/recommended',
  path: '/recommended',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsAppIdRoute = ApplicationsAppIdRouteImport.update({
  id: '/applications/$appId',
  path: '/applications/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCertificationsRoute = ProfileCertificationsRouteImport.update({
  id: '/profile/certifications',
  path: '/profile/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEducationRoute = ProfileEducationRouteImport.update({
  id: '/profile/education',
  path: '/profile/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileExperienceRoute = ProfileExperienceRouteImport.update({
  id: '/profile/experience',
  path: '/profile/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePreferencesRoute = ProfilePreferencesRouteImport.update({
  id: '/profile/preferences',
  path: '/profile/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileResumeRoute = ProfileResumeRouteImport.update({
  id: '/profile/resume',
  path: '/profile/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSkillsRoute = ProfileSkillsRouteImport.update({
  id: '/profile/skills',
  path: '/profile/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/jobs/$jobId/',
  path: '/jobs/$jobId/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdApplyRoute = JobsJobIdApplyRouteImport.update({
  id: '/jobs/$jobId/apply',
  path: '/jobs/$jobId/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdSuccessRoute = JobsJobIdSuccessRouteImport.update({
  id: '/jobs/$jobId/success',
  path: '/jobs/$jobId/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot': typeof ForgotRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recent': typeof RecentRoute
  '/recommended': typeof RecommendedRoute
  '/reset': typeof ResetRoute
  '/role': typeof RoleRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/applications/$appId': typeof ApplicationsAppIdRoute
  '/profile/certifications': typeof ProfileCertificationsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/education': typeof ProfileEducationRoute
  '/profile/experience': typeof ProfileExperienceRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/resume': typeof ProfileResumeRoute
  '/profile/skills': typeof ProfileSkillsRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/jobs/$jobId/success': typeof JobsJobIdSuccessRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot': typeof ForgotRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recent': typeof RecentRoute
  '/recommended': typeof RecommendedRoute
  '/reset': typeof ResetRoute
  '/role': typeof RoleRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/applications/$appId': typeof ApplicationsAppIdRoute
  '/profile/certifications': typeof ProfileCertificationsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/education': typeof ProfileEducationRoute
  '/profile/experience': typeof ProfileExperienceRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/resume': typeof ProfileResumeRoute
  '/profile/skills': typeof ProfileSkillsRoute
  '/applications': typeof ApplicationsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/jobs/$jobId/success': typeof JobsJobIdSuccessRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot': typeof ForgotRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recent': typeof RecentRoute
  '/recommended': typeof RecommendedRoute
  '/reset': typeof ResetRoute
  '/role': typeof RoleRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/applications/$appId': typeof ApplicationsAppIdRoute
  '/profile/certifications': typeof ProfileCertificationsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/education': typeof ProfileEducationRoute
  '/profile/experience': typeof ProfileExperienceRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/resume': typeof ProfileResumeRoute
  '/profile/skills': typeof ProfileSkillsRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/jobs/$jobId/success': typeof JobsJobIdSuccessRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot'
    | '/help'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/recent'
    | '/recommended'
    | '/reset'
    | '/role'
    | '/saved'
    | '/search'
    | '/session-expired'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/support'
    | '/terms'
    | '/verify'
    | '/welcome'
    | '/applications/$appId'
    | '/profile/certifications'
    | '/profile/edit'
    | '/profile/education'
    | '/profile/experience'
    | '/profile/preferences'
    | '/profile/resume'
    | '/profile/skills'
    | '/applications/'
    | '/jobs/'
    | '/profile/'
    | '/jobs/$jobId/apply'
    | '/jobs/$jobId/success'
    | '/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot'
    | '/help'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/recent'
    | '/recommended'
    | '/reset'
    | '/role'
    | '/saved'
    | '/search'
    | '/session-expired'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/support'
    | '/terms'
    | '/verify'
    | '/welcome'
    | '/applications/$appId'
    | '/profile/certifications'
    | '/profile/edit'
    | '/profile/education'
    | '/profile/experience'
    | '/profile/preferences'
    | '/profile/resume'
    | '/profile/skills'
    | '/applications'
    | '/jobs'
    | '/profile'
    | '/jobs/$jobId/apply'
    | '/jobs/$jobId/success'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/forgot'
    | '/help'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/recent'
    | '/recommended'
    | '/reset'
    | '/role'
    | '/saved'
    | '/search'
    | '/session-expired'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/support'
    | '/terms'
    | '/verify'
    | '/welcome'
    | '/applications/$appId'
    | '/profile/certifications'
    | '/profile/edit'
    | '/profile/education'
    | '/profile/experience'
    | '/profile/preferences'
    | '/profile/resume'
    | '/profile/skills'
    | '/applications/'
    | '/jobs/'
    | '/profile/'
    | '/jobs/$jobId/apply'
    | '/jobs/$jobId/success'
    | '/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ForgotRoute: typeof ForgotRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecentRoute: typeof RecentRoute
  RecommendedRoute: typeof RecommendedRoute
  ResetRoute: typeof ResetRoute
  RoleRoute: typeof RoleRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  WelcomeRoute: typeof WelcomeRoute
  ApplicationsAppIdRoute: typeof ApplicationsAppIdRoute
  ProfileCertificationsRoute: typeof ProfileCertificationsRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileEducationRoute: typeof ProfileEducationRoute
  ProfileExperienceRoute: typeof ProfileExperienceRoute
  ProfilePreferencesRoute: typeof ProfilePreferencesRoute
  ProfileResumeRoute: typeof ProfileResumeRoute
  ProfileSkillsRoute: typeof ProfileSkillsRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  JobsJobIdApplyRoute: typeof JobsJobIdApplyRoute
  JobsJobIdSuccessRoute: typeof JobsJobIdSuccessRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommended': {
      id: '/recommended'
      path: '/recommended'
      fullPath: '/recommended'
      preLoaderRoute: typeof RecommendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$appId': {
      id: '/applications/$appId'
      path: '/applications/$appId'
      fullPath: '/applications/$appId'
      preLoaderRoute: typeof ApplicationsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/certifications': {
      id: '/profile/certifications'
      path: '/profile/certifications'
      fullPath: '/profile/certifications'
      preLoaderRoute: typeof ProfileCertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/education': {
      id: '/profile/education'
      path: '/profile/education'
      fullPath: '/profile/education'
      preLoaderRoute: typeof ProfileEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/experience': {
      id: '/profile/experience'
      path: '/profile/experience'
      fullPath: '/profile/experience'
      preLoaderRoute: typeof ProfileExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/preferences': {
      id: '/profile/preferences'
      path: '/profile/preferences'
      fullPath: '/profile/preferences'
      preLoaderRoute: typeof ProfilePreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/resume': {
      id: '/profile/resume'
      path: '/profile/resume'
      fullPath: '/profile/resume'
      preLoaderRoute: typeof ProfileResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/skills': {
      id: '/profile/skills'
      path: '/profile/skills'
      fullPath: '/profile/skills'
      preLoaderRoute: typeof ProfileSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/apply': {
      id: '/jobs/$jobId/apply'
      path: '/jobs/$jobId/apply'
      fullPath: '/jobs/$jobId/apply'
      preLoaderRoute: typeof JobsJobIdApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/success': {
      id: '/jobs/$jobId/success'
      path: '/jobs/$jobId/success'
      fullPath: '/jobs/$jobId/success'
      preLoaderRoute: typeof JobsJobIdSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ForgotRoute: ForgotRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RecentRoute: RecentRoute,
  RecommendedRoute: RecommendedRoute,
  ResetRoute: ResetRoute,
  RoleRoute: RoleRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  WelcomeRoute: WelcomeRoute,
  ApplicationsAppIdRoute: ApplicationsAppIdRoute,
  ProfileCertificationsRoute: ProfileCertificationsRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileEducationRoute: ProfileEducationRoute,
  ProfileExperienceRoute: ProfileExperienceRoute,
  ProfilePreferencesRoute: ProfilePreferencesRoute,
  ProfileResumeRoute: ProfileResumeRoute,
  ProfileSkillsRoute: ProfileSkillsRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  JobsJobIdApplyRoute: JobsJobIdApplyRoute,
  JobsJobIdSuccessRoute: JobsJobIdSuccessRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
